# Generated by Django 3.2 on 2021-05-17 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(upload_to='Advisors/')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_time', models.DateTimeField(null=True)),
                ('advisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.advisors')),
            ],
        ),
    ]
